apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: project
type: Opaque
data:
  # echo -n "todouser" | base64
  username: dG9kb3VzZXI=
  # echo -n "todopass" | base64  
  password: dG9kb3Bhc3M=
  database: dG9kb2Ri
