apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-multi
  labels:
    app: log-output-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-multi
  template:
    metadata:
      labels:
        app: log-output-multi
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: log-writer
          image: log-writer:1.0
          volumeMounts:
            - name: shared-logs
              mountPath: /shared-logs
        - name: log-reader
          image: log-reader:1.11
          volumeMounts:
            - name: shared-logs
              mountPath: /shared-logs
            - name: shared-data
              mountPath: /shared-data
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
