apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: default
  labels:
    app: flask-app
    exercise: "4.10"
    owner: "ruwanfer"
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
    nodePort: 30080
