apiVersion: v1
kind: Pod
metadata:
  name: wikipedia
spec:
  volumes:
  - name: html
    emptyDir: {}
  
  initContainers:
  - name: get-page
    image: alpine/curl
    command: ["sh", "-c", "curl -s https://en.wikipedia.org/wiki/Kubernetes > /html/kubernetes.html"]
    volumeMounts:
    - name: html
      mountPath: /html

  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  
  - name: sidecar
    image: alpine/curl
    command: ["sh", "-c", "while true; do sleep \$((300 + RANDOM % 600)); curl -s https://en.wikipedia.org/wiki/Special:Random > /html/random-\$(date +%s).html; done"]
    volumeMounts:
    - name: html
      mountPath: /html
