apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ruwanfer/kubernetes-course-submissions.git
    targetRevision: HEAD
    path: log-output-multi/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: exercises
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
