apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: busybox
        command: ["sh", "-c", "while true; do echo 'Log App: Exercise 5.3 running'; sleep 30; done"]
