apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  # File content
  information.txt: |
    this text is from file
  
  # Environment variable
  MESSAGE: hello world
